[workspace]
members = [
    "crates/core",
    "crates/hooks",
    "crates/actions",
    "crates/constraints",
    "crates/script",
    "crates/store",
    "crates/app",
]
resolver = "2"

[workspace.dependencies]
koakuma-core        = { path = "crates/core" }
koakuma-hooks       = { path = "crates/hooks" }
koakuma-actions     = { path = "crates/actions" }
koakuma-constraints = { path = "crates/constraints" }
koakuma-script      = { path = "crates/script" }
koakuma-store       = { path = "crates/store" }

serde             = { version = "1", features = ["derive"] }
serde_json        = "1"
uuid              = { version = "1", features = ["v4", "serde"] }
thiserror         = "2"
crossbeam-channel = "0.5"
notify            = "6"
rhai              = "1"
slint             = "1.16.1"
async-trait       = "0.1"
futures           = "0.3"
tokio             = { version = "1", features = ["rt", "rt-multi-thread", "time", "macros"] }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
