[package]
name = "korkuma-app"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[[bin]]
name = "korkuma"
path = "src/main.rs"

[dependencies]
korkuma-core        = { workspace = true }
korkuma-hooks       = { workspace = true }
korkuma-actions     = { workspace = true }
korkuma-constraints = { workspace = true }
korkuma-script      = { workspace = true }
korkuma-store       = { workspace = true }
slint               = { workspace = true, features = ["renderer-femtovg", "renderer-software"] }
serde_json          = { workspace = true }
uuid                = { workspace = true }
crossbeam-channel   = { workspace = true }
notify              = { workspace = true }

[build-dependencies]
slint-build = "1.16.1"