[package]
name = "korkuma-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde             = { workspace = true }
serde_json        = { workspace = true }
uuid              = { workspace = true }
thiserror         = { workspace = true }
crossbeam-channel = { workspace = true }
async-trait       = { workspace = true }
futures           = { workspace = true }
tokio             = { workspace = true }

[dev-dependencies]
korkuma-store = { workspace = true }
tokio         = { workspace = true }
async-trait   = { workspace = true }